### ISSUE TITLE
Spring Security와 JWT를 이용한 사용자 권한별 접근 제어 구현

### ISSUE THREAD

**Issue by seven2762** [jabberwocker04/gitandrun#31]
## Description
JWT와 Spring Security를 활용한 권한(Role) 기반 인증/인가 기능 구현.
사용자 Role(CUSTOMER, OWNER, MANAGER, ADMIN)에 따라 API 접근 권한 부여.

## Todo
- [x] Spring Security 기본 설정
 - [x] SecurityConfig 구현
 - [x] UserDetails, UserDetailsService 구현
 - [x] PasswordEncoder 설정

- [x] JWT 관련 구현
 - [x] JWT 토큰 생성/검증 유틸 구현
 - [x] Access Token, Refresh Token 구현
 - [x] JWT 인증 필터 구현

- [x] Role 기반 접근 제어 구현
 - [x] Role별 접근 권한 설정
 - [x] API 엔드포인트별 권한 설정

- [x] 인증 관련 API 구현
 - [x] 로그인 API
 - [ ] 토큰 재발급 API
 - [ ] 로그아웃 API

- [ ] 예외 처리
 - [x] Security 관련 예외 처리 구현
 - [x] JWT 관련 예외 처리 구현

## ETC
프로젝트 규모로 따졌을때 실질적으로 ADMIN과 MANAGER의 역할을 구분하기 어려움...
