### ISSUE TITLE
Ai 엔티티 구현 생성 및 Create, Read(전체조회) 구현

### ISSUE THREAD

**Issue by jabberwocker04** [jabberwocker04/gitandrun#51]
## Description
요구사항 중 AI를 이용하는
- **상품 설명 자동 생성:** AI API를 연동하여 가게 사장님이 상품 설명을 쉽게 작성할 수 있도록 지원
- **AI 요청 기록:** AI API 요청 질문과 대답은 모두 데이터베이스에 저장
위의 두 영역을 구현하기 위해 Google Ai Gemini API 연동 후 Create, Read(전체조회) 구현.

## Todo
- [ ] AI API 연동 및 사용
- [ ] AI 질문 및 답변 생성 구현
- [ ] AI 질문 및 답변 조회 구현

## ETC
기타사항
