### ISSUE TITLE
주문 기능 리팩토링

### ISSUE THREAD

**Issue by ohsutinn** [jabberwocker04/gitandrun#67]
## Description
가독성있게 코드를 정리하고, 컨트롤러마다 권한 부여를 진행한다.
주문 생성 로직을 간결하게 수정한다.

## Todo
- [x] private 메서드 정리
- [x] API 접근 권한 설정
- [x] 주문 취소 및 거절 간 검증 구현
- [x] 주문 생성 로직 리팩토링

## ETC
기타사항
