### ISSUE TITLE
Store_id 추가 및 soft-delete 관리 방식 변경

### ISSUE THREAD

**Issue by soo1e** [jabberwocker04/gitandrun#77]
## Description
현재 조회시에는 store_id가 뜨지 않는 걸로 구현했는데 이를 보이도록 변경할 예정입니다.
또한 soft-delete된 데이터도 현재 id를 입력하고 들어가면 권한에 상관없이 보이도록 했는데 이를 고치는 김에 
관리자도 deleted / not deleted 필터링해서 볼 수 있게 새로 url을 구성하여 기능을 구현할 예정입니다.
또한 이러한 기능은 카테고리로 검색이나 키워드로 검색에서도 가능하도록 할 예정입니다.

## Todo
- [x] store_id 보이도록 dto 변경
- [x] soft-delete 데이터 필터링 (전체 검색)
- [x] soft-delete 데이터 필터링 (카테고리 검색)
- [x] soft-delete 데이터 필터링 (키워드 검색)

## ETC
💻
