### ISSUE TITLE
고객 결제 조회 기능 구현

### ISSUE THREAD

**Issue by ohsutinn** [jabberwocker04/gitandrun#82]
## Description
- `CUSTOMER` 의 결제 조회 기능을 구현합니다.
- `QueryDsl` 을 이용한 동적 쿼리를 구현합니다.

## Todo
- [x] 조회 간 가게 정보를 포함한 주문 정보가 명시되어야 한다.
- [x] 기본적으로 `PAID` 상태인 결제 목록을 조회한다.
- [x] `CANCEL` 상태 결제를 조회할 수 있어야 한다.
- [x] 최신순 / 오래된순 조회가 가능해야 한다.
- [x] 삭제된 결제는 조회할 수 없다.

## ETC
기타사항
