### ISSUE TITLE
결제 상세 조회 기능 구현

### ISSUE THREAD

**Issue by ohsutinn** [jabberwocker04/gitandrun#92]
## Description
- 특정 결제에 대한 상세 정보를 조회합니다.
- 모든 권한의 유저가 상세 정보를 조회할 수 있습니다.

## Todo
- [x] 모든 권한의 유저가 조회할 수 있다.
- [x] 결제 : 결제 Id / 결제 가격 / 상태 / 결제 일시 / (취소 여부) 조회
- [x] 주문 : 주문 Id / 상태 / 주문 형태 / 주문 일시 / 메뉴 목록 조회
- [x] 가게 : 가게 Id / 가게 이름 / 가게 위치 조회

## ETC
기타사항
