### ISSUE TITLE
주문 및 결제 기능 리팩토링 및 누락 기능 보완

### ISSUE THREAD

**Issue by ohsutinn** [jabberwocker04/gitandrun#94]
## Description
- 주문 및 결제 도메인에 대한 코드 리팩토링을 진행할 것입니다.
- 누락된 기능 혹은 보완할 기능을 발견하고, 해당 기능에 대한 수정조치를 진행하겠습니다.
- 앞서 주문과 가게 간의 관계에 변경점이 있었습니다. 이에 대한 주문 로직에 대한 일부 수정을 진행하겠습니다.

## Todo
- [x] 요청 DTO의 네이밍과 내부 구조를 일관되게 정리
- [x] 패키지 구조 일관되게 정리
- [x] 메서드 명명 규칙을 일관되게 정리
- [x] 주문 <-> 가게 관계 변경에 의한 주문 로직 수정
- [x] #100 
- [x] #106 
- [x] #108

## ETC
기타사항
