### ISSUE TITLE
Docker 를 이용한 자동 배포 환경 구축

### ISSUE THREAD

**Issue by ohsutinn** [jabberwocker04/gitandrun#95]
## Description
- `Docker` 를 활용하여 서비스의 자동 배포 환경을 구축합니다
- `GitHub Actions` 를 활용하여 파이프라인을 구성할 것입니다.

## Todo
- [ ] `Dockerfile` 작성
- [ ] `Docker Compose` 작성
- [ ]  배포 스크립트 작성
- [ ] `Secretes` 활용하여 환경 변수 및 민감 정보 관리
- [ ] (선택) 이미지 사이즈 최적화

## ETC
기타사항
